@heading API reference
@itemize @bullet
@item
The @emph{GNU libmicrohttpd} manual by Marco Maggi and Christian Grothoff
@uref{https://www.gnu.org/software/libmicrohttpd/manual/libmicrohttpd.html}

@item
All referenced RFCs can be found on the website of @emph{The Internet Engineering Task Force}
@uref{https://www.ietf.org/}

@item
@emph{RFC 2616}: Fielding, R., Gettys, J., Mogul, J., Frystyk, H., Masinter, L., Leach, P.,
and T. Berners-Lee, "Hypertext Transfer Protocol -- HTTP/1.1", RFC 2616, June 1999.

@item
@emph{RFC 2617}: Franks, J., Hallam-Baker, P., Hostetler, J., Lawrence, S., Leach, P.,
Luotonen, A., and L. Stewart, "HTTP Authentication: Basic and Digest Access Authentication", RFC 2617, June 1999.

@item
@emph{RFC 6455}: Fette, I., Melnikov, A., "The WebSocket Protocol", RFC 6455, December 2011.


@item
A well--structured @emph{HTML} reference can be found on
@uref{http://www.echoecho.com/html.htm}

For those readers understanding German, there is an excellent document both for learning
@emph{HTML} and for reference, whose English and French versions unfortunately have been
discontinued.
@uref{https://wiki.selfhtml.org/}


@end itemize
